### PR TITLE
Pull out senders from view servlet

### PR DESCRIPTION
**Pull request by cstamas**
To simplify code and testing

CI
http://bamboo.s/browse/NX3-OSSF354

### CODE REVIEW

**Comment by mrprescott** [comment]
+1 What's good for the goose is good for the gander, I guess!

**Comment by cstamas** [comment]
http://bamboo.s/browse/NX3-OSSF354-1 :+1:

**Comment by jdillon** [comment]
purpose of which is?

**Comment by mcculls** [comment]
@jdillon it's a pattern from today's storageTx PR - originally it was passing around a map of validators and a default validator with the selection done as a private method. Michael and I suggested extracting that out as a selector (https://github.com/sonatype/nexus-oss/commit/a3269aec8f728a66cd722aad9a46e38ac50e78c3) and Tamas is applying the same pattern here. What's your view on this pattern?

**Comment by jdillon** [comment]
@mcculls no issue extracting out simple discrete components, just was not clear why it was needed based on the changes in this PR.

**Pull request merged**
