### PR TITLE
NEXUS-8607 maven site deploy

### PR DESCRIPTION
**Pull request by mrprescott**
https://issues.sonatype.org/browse/NEXUS-8607

### CODE REVIEW

**Comment by mrprescott** [comment]
http://bamboo.s/browse/NX3-OSSF339-3 :white_check_mark:

**Comment by jdillon** [comment]
+1

we may want to consider options to share some of these example/test projects so we don't end up littering poms and test app code throughout the testsuite codebase (as we did in the past).

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by mrprescott** [comment]
Rebased as #1355

**Pull request closed without merging**
