### PR TITLE
Drop unused deps from nexus-cache

### PR DESCRIPTION
**Pull request by jdillon**

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF621-1 unrelated FT failure

**Comment by jdillon** [comment]
Hrm.... maybe some of these are needed, now seeing missing TX dep wiring WTF :-(

**Pull request merged**
