### PR TITLE
Kill legacy indexer

### PR DESCRIPTION
**Pull request by mcculls**
Remove nexus-indexer-lucene-plugin, nexus-maven-bridge-plugin and nexus-archetype-plugin.
These were the last plugins that needed our pseudo-Plexus facade so that can go away too.

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by sgandon** [comment]
Hello,
I am sorry to use this channel but I'd like to know why the nexus-indexer-lucene-plugin has been removed ? what is the replacement and where can I find it ?
Thanks very much.

**Comment by mcculls** [comment]
@sgandon you should use the nexus-2.11.x branch if you're looking at Nexus 2, ie. https://github.com/sonatype/nexus-oss/tree/nexus-2.11.x/plugins/indexer/nexus-indexer-lucene-plugin/

Nexus 3 will use a new search mechanism based on elasticsearch. If you need more details please ask on the mailing list: https://groups.google.com/a/glists.sonatype.com/forum/?hl=en#!forum/nexus-users

**Comment by sgandon** [comment]
Thanks a lot.

**Pull request merged**
