### PR TITLE
Upgrade to Karaf 3.0.3

### PR DESCRIPTION
**Pull request by mcculls**
Karaf 3.0.3 is staged, but not yet released (voting is in progress). These are the changes I used to test the staged release locally. List of fixes in this patch release: http://svn.apache.org/viewvc/karaf/site/trunk/src/main/webapp/index/community/download/karaf-3.0.3-release.page?view=markup

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1 seems pretty straightforward

**Comment by mrprescott** [comment]
+1

**Comment by jdillon** [comment]
+1 once its on central

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
