### PR TITLE
Remove capabilities rest endpoint

### PR DESCRIPTION
**Pull request by jdillon**
related:
https://github.com/sonatype/nexus-pro/pull/555

### CODE REVIEW

**Comment by mcculls** [comment]
+1  (btw, is there a related story?)

**Comment by mrprescott** [comment]
+1

**Comment by jdillon** [comment]
@mcculls no story, I just noticed that it was still there, not used by anything, with a copy of model-like stuff that wasn't used.  I think this was left over for a short-wile for some of the legacy tests that were using REST to control capabilities?

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
