### PR TITLE
Prefix default maven repos with 'maven-'.  Use https for maven-central

### PR DESCRIPTION
**Pull request by jdillon**
Since we are aiming to be non-mvn specific set the default repos to follow format type prefix.
Use https for maven-central.

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1

**Comment by mrprescott** [comment]
+1

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF178-1 :white_check_mark:

**Comment by jdillon** [comment]
manually merged

**Comment by adreghiciu** [comment]
+1

**Pull request closed without merging**
