### PR TITLE
Support integer model ids when navigating drilldown bookmarks

### PR DESCRIPTION
**Pull request by mcculls**
Discovered while working on https://issues.sonatype.org/browse/NEXUS-8903 - if you drilldown to a specific bundle and then reload the page you get an error in the UI because the selected model is null.

Traced this back to the bookmark support in Drilldown.js which encodes the model id in the URL and later on decodes that id to find the selected model. This means the id used to select the model when navigating the bookmark is always a 'string'... so if the id property is actually an 'int' (as in the Bundle case) the model won't be found.

This was the simplest solution I found, but I'd be interested to hear of other ways to solve this.

Update: https://github.com/sonatype/nexus-oss/pull/1515 is another solution suggested by @kellyrob99 

http://bamboo.s/browse/NX3-OSSF509-1 (unrelated FT failure)

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1
Alternatively we could change the model to keep the id as a string on the client, should work just the same.

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
Closing in favour of https://github.com/sonatype/nexus-oss/pull/1515

**Comment by jdillon** [comment]
Model id can be a string or a number:

http://docs.sencha.com/extjs/4.2.3/#!/api/Ext.data.Model-method-getId

So while the other PR may be simpler for this one problem, doesn't help solve if another model comes along with number ids (which are totally valid).

**Comment by mcculls** [comment]
Merged to master as 641b5f6

**Pull request closed without merging**
