### PR TITLE
NEXUS-8920 rename archived request log to be sane

### PR DESCRIPTION
**Pull request by peterlynch**
https://issues.sonatype.org/browse/NEXUS-8920

### CODE REVIEW

**Comment by jdillon** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by mcculls** [comment]
Note: logback-nexus.xml still uses the original style, but is harder to change as it uses `${appender.file}` in the filename pattern.

**Comment by peterlynch** [comment]
yeah ${appender.file}.%d{yyyy-MM-dd}.gz sucks for nexus.log

we could change it to ${appender.file}-%d{yyyy-MM-dd}.log.gz without too much stress I suspect, but would only do that in another issue after discussion. Likely will just fix it in Nexus 3.

**Pull request merged**
