### PR TITLE
Priv property injection

### PR DESCRIPTION
**Pull request by jdillon**
Remove use of injection for privilege properties.

Noticed these were all injected, but couldn't find a good reason why.  These property descriptors are also not used by anything in NX3 ATM (okay one place, in a legacy REST end-point PrivilegeTypePlexusResource thats all).

So to simplify things more, I removed the use of injection and simply returned new instances when a priv is asked for these to retain compatibility with the PrivilegeTypePlexusResource impl.

### CODE REVIEW

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX-OSSF503-1 :white_check_mark: 

There is a small change to nexus-pro to apply same thing, but will likely just commit that once this is merged.

**Comment by mcculls** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Pull request merged**
