### PR TITLE
[NEXUS-8488] Recreate repository http client when global http config change

### PR DESCRIPTION
**Pull request by adreghiciu**
Somehow related https://issues.sonatype.org/browse/NEXUS-8488

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
any implications of state corruption?

**Comment by adreghiciu** [comment]
When facet is stopped (e.g. reconfiguration), the facet is unsubscribed so there will be no events received

**Comment by jdillon** [comment]
+1

**Pull request merged**
