### PR TITLE
NEXUS-8920 rename archived request log to be sane

### PR DESCRIPTION
**Pull request by peterlynch**
https://issues.sonatype.org/browse/NEXUS-8920

### CODE REVIEW

**Comment by jdillon** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1

Note: `logback-nexus.xml` and the bootstrapping `logback.xml` (only active before nexus starts) still use the original style, but it should be straightforward to change them for the sake of consistency.

**Pull request merged**
