### PR TITLE
Use geronimo jcache spec

### PR DESCRIPTION
**Pull request by jdillon**
Uses ASF licensed jcache spec dependency instead of oddly licensed javax.cache version.

### CODE REVIEW

**Comment by jdillon** [comment]
```
2015-07-29 11:29:41,303-0700 ERROR [jetty-main-1] *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Failed to start
java.lang.RuntimeException: java.lang.Exception: Could not start bundle mvn:org.sonatype.nexus/nexus-security/3.0.0-SNAPSHOT in feature(s) nexus-base-edition-3.0.0-SNAPSHOT: Unresolved constraint in bundle org.sonatype.nexus.security [111]: Unable to resolve 111.0: missing requirement [111.0] osgi.wiring.package; (&(osgi.wiring.package=javax.cache)(version>=1.0.0)) [caused by: Unable to resolve 119.0: missing requirement [119.0] osgi.wiring.package; (&(osgi.wiring.package=javax.enterprise.util)(version>=1.0.0)) [caused by: Unable to resolve 120.0: missing requirement [120.0] osgi.wiring.package; (&(osgi.wiring.package=javax.inject)(version>=1.0.0))]]
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:139) [org.sonatype.nexus.bootstrap:3.0.0.SNAPSHOT]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800) [org.eclipse.jetty.server:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) [org.eclipse.jetty.servlet:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791) [org.eclipse.jetty.server:9.2.9.v20150224]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) [org.eclipse.jetty.servlet:9.2.9.v20150224]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349) [org.eclipse.jetty.webapp:9.2.9.v20150224]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342) [org.eclipse.jetty.webapp:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) [org.eclipse.jetty.server:9.2.9.v20150224]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505) [org.eclipse.jetty.webapp:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [org.eclipse.jetty.server:9.2.9.v20150224]
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:92) [com.codahale.metrics.jetty9:3.0.2]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [org.eclipse.jetty.server:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.server.Server.start(Server.java:387) [org.eclipse.jetty.server:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [org.eclipse.jetty.server:9.2.9.v20150224]
	at org.eclipse.jetty.server.Server.doStart(Server.java:354) [org.eclipse.jetty.server:9.2.9.v20150224]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [org.eclipse.jetty.util:9.2.9.v20150224]
	at org.sonatype.nexus.bootstrap.jetty.JettyServer$JettyMainThread.run(JettyServer.java:277) [org.sonatype.nexus.bootstrap:3.0.0.SNAPSHOT]
Caused by: java.lang.Exception: Could not start bundle mvn:org.sonatype.nexus/nexus-security/3.0.0-SNAPSHOT in feature(s) nexus-base-edition-3.0.0-SNAPSHOT: Unresolved constraint in bundle org.sonatype.nexus.security [111]: Unable to resolve 111.0: missing requirement [111.0] osgi.wiring.package; (&(osgi.wiring.package=javax.cache)(version>=1.0.0)) [caused by: Unable to resolve 119.0: missing requirement [119.0] osgi.wiring.package; (&(osgi.wiring.package=javax.enterprise.util)(version>=1.0.0)) [caused by: Unable to resolve 120.0: missing requirement [120.0] osgi.wiring.package; (&(osgi.wiring.package=javax.inject)(version>=1.0.0))]]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:521) [na:na]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:476) [na:na]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:417) [na:na]
	at Proxy553a380d_22c0_4106_be1b_0010f35024ae.installFeature(Unknown Source) [na:na]
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.installNexusEdition(BootstrapListener.java:158) [org.sonatype.nexus.bootstrap:3.0.0.SNAPSHOT]
	at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:124) [org.sonatype.nexus.bootstrap:3.0.0.SNAPSHOT]
	... 25 common frames omitted
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle org.sonatype.nexus.security [111]: Unable to resolve 111.0: missing requirement [111.0] osgi.wiring.package; (&(osgi.wiring.package=javax.cache)(version>=1.0.0)) [caused by: Unable to resolve 119.0: missing requirement [119.0] osgi.wiring.package; (&(osgi.wiring.package=javax.enterprise.util)(version>=1.0.0)) [caused by: Unable to resolve 120.0: missing requirement [120.0] osgi.wiring.package; (&(osgi.wiring.package=javax.inject)(version>=1.0.0))]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974) [na:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037) [na:na]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955) [na:na]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:942) [na:na]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:518) [na:na]
	... 30 common frames omitted
```

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF620-1 :white_check_mark:

**Comment by kellyrob99** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
