### PR TITLE
NEXUS-8361 - Create ExtJS facet views which add fields based on what the...

### PR DESCRIPTION
**Pull request by kellyrob99**
remove hack for double conversion

:+1: by CI 
http://bamboo.s/browse/NX3-OSSF209-1

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by mrprescott** [comment]
+1

**Comment by jdillon** [comment]
thank you @kellyrob99

**Comment by kellyrob99** [comment]
no, thank YOU @jdillon :)

**Pull request merged**
