### PR TITLE
NEXUS-8900 metrics functional tests

### PR DESCRIPTION
**Pull request by bradbeck**
https://issues.sonatype.org/browse/NEXUS-8900

### CODE REVIEW

**Comment by kellyrob99** [comment]
Missing a Java class to hook it up for CI , see https://github.com/sonatype/nexus-oss/blob/NEXUS-8900-metrics-ft/testsuite/functional-testsuite/src/test/java/org/sonatype/nexus/testsuite/SystemIT.java for an example

**Comment by bradbeck** [comment]
@kellyrob99 I added the corresponding `SupportIT.java`.

**Comment by kellyrob99** [comment]
+1 sufficient for a smoke test of the feature, please run and link a CI feature build to confirm things are wired up properly

**Comment by bradbeck** [comment]
Need to retarget the PR to master...

**Pull request closed without merging**
