### PR TITLE
Re-implement "activeBundles" state with OSGI BundleTracker

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-8648

### CODE REVIEW

**Comment by jdillon** [comment]
thanks @mcculls for your help to learn how to use this api :-)

**Comment by mcculls** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
