### PR TITLE
NEXUS-7966 Give mode buttons carets to tie them to the rest of the page

### PR DESCRIPTION
**Pull request by djsauble**
Issue: https://issues.sonatype.org/browse/NEXUS-7966

Changes:
+ Adds caret to mode buttons
+ Moves the “User” mode next to the other modes
+ Removes the user name from the user mode button. This isn’t useful.
+ Adds a “Sign out” label to the sign out button

Before:
welcome - sonatype nexus 2015-01-20 17-05-48

After:
welcome - sonatype nexus 2015-01-20 17-04-47

### CODE REVIEW

**Comment by jdillon** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by djsauble** [comment]
Manual merge: https://github.com/sonatype/nexus-oss/commit/d26e73c8cee2a0595ce3ad3407db0c64156151ef

**Pull request closed without merging**
