### PR TITLE
Addressing some sonar/IDE warnings

### PR DESCRIPTION
**Pull request by mrprescott**

### CODE REVIEW

**Comment by mcculls** [comment]
+1 ... just out of curiosity, which sonar rule detected that the bucket parameter could be removed in favour of getting it from the transaction when you actually needed it?

**Comment by bradbeck** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by mrprescott** [comment]
@mcculls Nothing exotic, it started as 'unused method parameter' warning somewhere along that chain.

**Comment by mrprescott** [comment]
http://bamboo.s/browse/NX3-OSSF419-1 :white_check_mark:

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
