### PR TITLE
NEXUS-8714 Nuget package fetching fixes

### PR DESCRIPTION
**Pull request by mrprescott**
https://issues.sonatype.org/browse/NEXUS-8714

### CODE REVIEW

**Comment by mrprescott** [comment]
http://bamboo.s/browse/NX3-OSSF380-1 :white_check_mark:

**Comment by mcculls** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by mrprescott** [comment]
Manually merged 9f142c6

**Pull request closed without merging**
