### PR TITLE
Evict bundles on restart

### PR DESCRIPTION
**Pull request by mcculls**
As part of the shutdown process we stop our extender/tracker when the context is destroyed,
which triggers removal events for any bundles it was tracking. Before this change we used
the bundle state to decide whether to evict the bundle (ie. remove its components from the
bean locator) and we ignored the eviction of any bundles during shutdown because of legacy
components which needed stability.

Now we forcibly evict bundles when we know we're stopping regardless of their actual state.
Note: some bundles can still be in active state at the time the tracker is stopped because
at the time the context is destroyed the framework start level has not yet dropped to zero.

http://bamboo.s/browse/NX3-OSSF373-1

### CODE REVIEW

**Comment by jdillon** [comment]
+1 seems to work, a few issues we'll have to sort out:

* siesta resources do not unregister
* manual mbean registration causes exceptions, use nexus-jmx framework instead: https://github.com/sonatype/nexus-pro/issues/553

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF373-1 :white_check_mark:

**Comment by cstamas** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by mcculls** [comment]
Added support for unregistration of siesta providers: https://github.com/sonatype/siesta/pull/24

**Comment by jdillon** [comment]
should be mergable now

**Comment by jdillon** [comment]
+1 lets update the since tags, can leave header for larger change

**Comment by mcculls** [comment]
http://bamboo.s/browse/NX3-OSSF373-2 :white_check_mark:

**Comment by mcculls** [comment]
Merged to master as 3c5c99c

**Pull request closed without merging**
