### PR TITLE
[NEXUS-8238] Repository Configuration Form Validation

### PR DESCRIPTION
**Pull request by adreghiciu**
https://issues.sonatype.org/browse/NEXUS-8232
http://bamboo.s/browse/NX3-OSSF196

### CODE REVIEW

**Comment by adreghiciu** [comment]
CI :+1: http://bamboo.s/browse/NX3-OSSF196-1

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
@adreghiciu does this account for the bean-validation key style of attributes[name].field ?

**Comment by adreghiciu** [comment]
@jdillon yes

**Comment by jdillon** [comment]
+1

**Comment by adreghiciu** [comment]
Manually merged as https://github.com/sonatype/nexus-oss/commit/cee8be9674f4e2f5fc1b25c2036d84f1fdb86940

**Pull request closed without merging**
