### PR TITLE
Performance improvements for drilldown

### PR DESCRIPTION
**Pull request by djsauble**
+ Improves response time (~40%) when drilling down
+ Improves response time (~40%) when selecting a feature in the menu that implements drilldown
+ Fixes memory leak when switching to and from the same drilldown-based feature
+ Moves drilldown logic from the view to the controller

Replaces https://github.com/sonatype/nexus-oss/pull/1486

### CODE REVIEW

**Comment by jdillon** [comment]
Seeing some problems

https://www.evernote.com/l/ABLV0nZpE9dJNb7hxs9e7J-LRW8qxrBFPw8
http://screencast.com/t/w2RddtGcd

**Comment by jdillon** [comment]
master does not seem to have these problems, so something in this refactor have broken that.

aslo, could just be me, but this branch feels much more sluggish than master when drilling down into items.

**Comment by djsauble** [comment]
Ready for another round of review.

**Comment by jdillon** [comment]
+1 seems faster and no longer seeing strange problems.

**Comment by mcculls** [comment]
+1 tested locally, looks ok

**Pull request closed without merging**
