### PR TITLE
Cleanup xstream (use official jar, plus xpp3 from servicemix)

### PR DESCRIPTION
**Pull request by mcculls**
http://bamboo.s/browse/NX3-OSSF334-1 :white_check_mark:

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by jdillon** [comment]
+1, though I think its still needed by insight dependencies for pro dist (or do they shade in xstream)?

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
Merged to master as 122a91d

**Pull request closed without merging**
