### PR TITLE
NEXUS-7959 fixes column hide, reorder, and resize

### PR DESCRIPTION
**Pull request by djsauble**
Issue:
https://issues.sonatype.org/browse/NEXUS-7959

Fixes:
Navigate on hide/show (http://take.ms/3Svy5)
Stale data on reorder (http://take.ms/pbERY)
Expanding beyond the browser window (http://take.ms/6T3Sr)

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by djsauble** [comment]
Manual merge. https://github.com/sonatype/nexus-oss/commit/ca8b83d06e225e14bdeef3e3920e674f73659712

**Pull request closed without merging**
