### PR TITLE
[NEXUS-8929] Browse UI permissions

### PR DESCRIPTION
**Pull request by adreghiciu**
https://issues.sonatype.org/browse/NEXUS-8929
http://bamboo.s/browse/NX3-OSSF537

Browse ui will now be shown when the user has repository-view browse on at least one repository and will show only those repositories on which the user has repository-view browse

### CODE REVIEW

**Comment by adreghiciu** [comment]
CI :+1: http://bamboo.s/browse/NX3-OSSF537-1

**Comment by jdillon** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by adreghiciu** [comment]
Manually merged as https://github.com/sonatype/nexus-oss/commit/86f6b3fde936de747f467976b9a84fe7678314be

**Pull request closed without merging**
