### PR TITLE
Graceful handling of unfetched blobs

### PR DESCRIPTION
**Pull request by mrprescott**
Discovered during testing of: https://issues.sonatype.org/browse/NEXUS-8611
NuGet proxies need to expect that sometimes assets will exist with no blobs.

### CODE REVIEW

**Comment by mcculls** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by mrprescott** [comment]
http://bamboo.s/browse/NX3-OSSF384-2/ :white_check_mark:

**Pull request merged**
