### PR TITLE
[NEXUS-7860] attach userId during NexusBaseHttpAuthenticationFilter.onLoginSuccess

### PR DESCRIPTION
**Pull request by mcculls**
[port of https://github.com/sonatype/nexus-oss/pull/1360 to nx3]

https://issues.sonatype.org/browse/NEXUS-7860
http://bamboo.s/browse/NX3-OSSF357-1 :white_check_mark: 

This handles the case where a subject is not logged in at the time of `SecurityFilter.executeChain`, but is logged in after a challenge is sent. As `SecurityFilter` is not re-executed we need to attach the userId during `NexusBaseHttpAuthenticationFilter.onLoginSuccess`.

This lines up with the two uses of `UserIdMdcHelper.set`: once in `SecurityFilter.executeChain` and once in `NexusWebSecurityManager.login` (which is called from `NexusBaseHttpAuthenticationFilter for login attempts`).

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by mcculls** [comment]
Merged to master as 4dfa8f4

**Pull request closed without merging**
