### PR TITLE
NEXUS-5904: Remove mirrors tab

### PR DESCRIPTION
**Pull request by cstamas**
And the remnants of it, as proxy mirrors were removed long time
ago.

Issue
https://issues.sonatype.org/browse/NEXUS-5904

### CODE REVIEW

**Comment by jdillon** [comment]
+1 if ui functions w/o any js errors

**Comment by kellyrob99** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
