### PR TITLE
Bump to HttpClient 4.4.1

### PR DESCRIPTION
**Pull request by cstamas**
Seems should solve the retries problem

See
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310360&version=12329394

CI
http://bamboo.s/browse/NX3-OSSF137

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by jdillon** [comment]
+1 w/feature build sanity

**Comment by cstamas** [comment]
http://bamboo.s/browse/NX3-OSSF137-2 :+1:

**Pull request merged**
