### PR TITLE
[NEXUS-7862] Update all email addresses in default/test -> @example.org

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-7862

related:

* https://github.com/sonatype/nexus-pro/pull/524
* https://github.com/sonatype/nexus-bundles/pull/137

### CODE REVIEW

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF201 :white_check_mark:

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1

**Pull request merged**
