### PR TITLE
[NEXUS-8586] preload OrientDB using empty TCCL so javax.script engines can be found

### PR DESCRIPTION
**Pull request by mcculls**
https://issues.sonatype.org/browse/NEXUS-8586
http://bamboo.s/browse/NX3-OSSF428-1 :white_check_mark:

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
Merged to master as 92ab6eb

**Pull request closed without merging**
