### PR TITLE
Cleaner way to generate slimmer ehcache bundle

### PR DESCRIPTION
**Pull request by mcculls**
Rebuild from selected sources so we know they form a consistent set of classes.

Also avoids an issue when building with recent versions of Maven where the original ehcache bundle can end up in the final assembly because Maven picks up the original reactor pom, rather than the reduced pom installed by the shade plugin.

### CODE REVIEW

**Comment by cstamas** [comment]
I wonder how something using `build-helper-maven-plugin` can be seen as _trivial_ :smile: 

+1

**Comment by bradbeck** [comment]
+1

**Comment by mcculls** [comment]
Created another alternative at https://github.com/sonatype/nexus-oss/pull/1620 which people might prefer as it's closer to the original approach.

**Comment by mcculls** [comment]
Closing in favour of https://github.com/sonatype/nexus-oss/pull/1620

**Pull request closed without merging**
