### PR TITLE
NEXUS-8267 - NuGet feed data contains unexpected attribute key

### PR DESCRIPTION
**Pull request by kellyrob99**
- trivial addition of 'alias' for DOWNLOADCOUNT property

https://issues.sonatype.org/browse/NEXUS-8267

### CODE REVIEW

**Comment by djsauble** [comment]
What different purposes do `DOWNLOAD_COUNT` and `DOWNLOAD_COUNT_ALIAS` serve?

**Comment by kellyrob99** [comment]
@djsauble in some cases the underlying data says its property name for the orderBy is DOWNLOAD_COUNT and our expectation was that it is called DOWNLOADCOUNT. This only happens for some records

**Comment by djsauble** [comment]
+1

**Comment by cwilper** [comment]
+1

**Pull request merged**
