### PR TITLE
NEXUS-8016 Group member compatibility

### PR DESCRIPTION
**Pull request by mrprescott**
https://issues.sonatype.org/browse/NEXUS-8016

### CODE REVIEW

**Comment by cstamas** [comment]
+1, but this change does not really ensure that group repositories can only have compatible constituent repos nor relies on validation API :smile:

**Comment by mrprescott** [comment]
Agreed, it's a reduction in scope essentially.

**Comment by mrprescott** [comment]
http://bamboo.s/browse/NX3-OSSF162-1 :white_check_mark:

**Comment by jdillon** [comment]
@cstamas the UI can/should ensure that you can't configure invalid repos in a group, the logic here is just to prevent manually tampered configuration from doing things it shouldn't.  We can revisit later but this is the minimal simplest change to meet the underlying needs.

**Comment by jdillon** [comment]
+1 much simpler

**Pull request merged**
