### PR TITLE
[nexus-2.11.x] Upgrade to OrientDB 2.0

### PR DESCRIPTION
**Pull request by mcculls**
(and use OPartitionedDatabasePool instead of deprecated ODatabaseDocumentPool)

https://issues.sonatype.org/browse/NEXUS-7974
http://bamboo.s/browse/NX-OSSF511-1 :white_check_mark:

### CODE REVIEW

**Comment by cstamas** [comment]
@mcculls Thanks! I believe transition from 1.7.10 to 2.0 is seamless re existing databases?

**Comment by cstamas** [comment]
http://bamboo.s/browse/NX-OSSF511-1 :+1:

**Comment by mcculls** [comment]
@cstamas yes, according to http://www.orientechnologies.com/docs/last/orientdb.wiki/Migration-from-1.7.x-to-2.0.x.html "Databases created with release 1.7.x are compatible with 2.0"

**Comment by kellyrob99** [comment]
They do specify an export/import step (on the page Stuart linked) if you
want the new 'binary serialization' that is supposed to be 20% faster.

**Comment by mcculls** [comment]
Note that you only need to export+re-import if you want the boost from the new protocol - the protocol performance without this step is effectively the same as in 1.7. The main reason for the upgrade is the improvements to the write-ahead-log recovery, which doesn't require any manual change to the DB.

**Comment by jdillon** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Pull request closed without merging**
