### PR TITLE
Adds title/description strings for Upload -> Nuget

### PR DESCRIPTION
**Pull request by djsauble**
Issue: https://issues.sonatype.org/browse/NEXUS-7874

Before:
- sonatype nexus 2015-01-21 16-52-14

After:
nuget - sonatype nexus 2015-01-21 16-50-58

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by djsauble** [comment]
Manual merge. https://github.com/sonatype/nexus-oss/commit/dfa74c4ceaf3d685de3f90b730a62f02f6a969ba

**Comment by adreghiciu** [comment]
+1

**Pull request closed without merging**
