### PR TITLE
NEXUS-8971: Reuse the Content returned by merge method (is reusable on purpose)

### PR DESCRIPTION
**Pull request by cstamas**
So, reuse it. This fixes the bug that under load, group may respond
with 404 for a request that should be successful, as it was making
redundant roundtrip to Storage (by doing PUT/GET) instead reusing
the merged content as is.

Issue
https://issues.sonatype.org/browse/NEXUS-8971

CI
http://bamboo.s/browse/NX3-OSSF576

### CODE REVIEW

**Comment by cstamas** [comment]
http://bamboo.s/browse/NX3-OSSF576-1 :+1:

**Comment by mcculls** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
Merged as c8542320258befbb274c4825d6f180134a4eb8a5

**Pull request closed without merging**
