### PR TITLE
Update to OrientDB 2.1-rc6

### PR DESCRIPTION
**Pull request by mcculls**
Contains all our suggested fixes: https://github.com/orientechnologies/orientdb/issues?q=milestone%3A2.1-rc6+is%3Aclosed

http://bamboo.s/browse/NX3-OSSF614-1

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by bradbeck** [comment]
+1

**Comment by cstamas** [comment]
+1

thanks (phone),
~t~

**Comment by mcculls** [comment]
Merged to master as 2fec9ba

**Pull request closed without merging**
