### PR TITLE
[NEXUS-7791] remove xercesImpl from distribution

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-7791

### CODE REVIEW

**Comment by mcculls** [comment]
+1 ... it does leave some unused exports relating to xerces in config.properties, but these shouldn't cause any problems since nothing we use requires them.

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
@mcculls can you point me at where?

**Comment by mcculls** [comment]
@jdillon for reference see the original change that added xerces as an endorsed library: http://svn.apache.org/viewvc/karaf/trunk/assemblies/features/framework/src/main/filtered-resources/resources/etc/config.properties?r1=1520994&r2=1520993&pathrev=1520994

Both `org.osgi.framework.system.packages.extra` and `org.osgi.framework.bootdelegation` refer to xerces packages. With xerces removed these are now dangling references, but in practice shouldn't cause any issues since we don't use any of them atm.

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by cwilper** [comment]
+1

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF87-1 :white_check_mark:

**Pull request merged**
