### PR TITLE
NEXUS-8850 log uptime at Nexus shutdown initialization

### PR DESCRIPTION
**Pull request by peterlynch**
adjust location to log earlier

https://issues.sonatype.org/browse/NEXUS-8850

### CODE REVIEW

**Comment by peterlynch** [comment]
augments https://github.com/sonatype/nexus-oss/pull/1455

**Comment by kellyrob99** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1

**Pull request merged**
