### PR TITLE
NEXUS-8749 Nuget proxy mangling remote communication errors

### PR DESCRIPTION
**Pull request by mrprescott**
Two things fixed:
a) Nuget had no implementation for getUrl(), so constructing a message for IOException would itself throw an exception
b) When a proxy can't fetch an uncached artifact due to IOException, it now reports HTTP 502 (bad gateway) rather than 503 (service unavailable)

### CODE REVIEW

**Comment by mcculls** [comment]
+1 ... would be good to get the teams consensus on what response should be sent when the upstream is misbehaving, but we could always merge in the NuGet specific fix and leave the status change for another day

**Comment by jdillon** [comment]
seems reasonable

**Comment by mrprescott** [comment]
http://bamboo.s/browse/NX3-OSSF389-1 :white_check_mark:

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
