### PR TITLE
[NEXUS-8783] Set proper editable condition for tasks

### PR DESCRIPTION
**Pull request by adreghiciu**
https://issues.sonatype.org/browse/NEXUS-8783

### CODE REVIEW

**Comment by djsauble** [comment]
+1

**Comment by kellyrob99** [comment]
+1, provided #1411 doesn't conflict

**Comment by joedragons** [comment]
Note, NEXUS-8783 comment mentions this occurs as well for LDAP (unless you've found that not true or prefer another ticket then let me know).  It looks like this solution may just be for tasks, tho obviously, my eye is not expert to code changes.  2 cents.

**Comment by mcculls** [comment]
@joedragons FYI https://github.com/sonatype/nexus-oss/pull/1415 is the related change for LDAP (and https://github.com/sonatype/nexus-oss/pull/1413 for capabilities)

**Comment by joedragons** [comment]
Thanks @mcculls.  Going to update the ticket=)

**Pull request merged**
