### PR TITLE
[NEXUS-8903] bundles functional tests

### PR DESCRIPTION
**Pull request by mcculls**
https://issues.sonatype.org/browse/NEXUS-8903
http://bamboo.s/browse/NX3-OSSF512-1 (unrelated failure in different FT)

### CODE REVIEW

**Comment by bradbeck** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by mcculls** [comment]
Merged to master as ea5de01

**Pull request closed without merging**
