### PR TITLE
NEXUS-7819 Do not allow mode buttons to be deselected

### PR DESCRIPTION
**Pull request by djsauble**
Issue: https://issues.sonatype.org/browse/NEXUS-7819

Before: http://take.ms/UBG0L

After: http://take.ms/OwhXp

### CODE REVIEW

**Comment by jdillon** [comment]
video shows user mode button moved, is that part of this change?

**Comment by djsauble** [comment]
@jdillon Nope, part of https://github.com/sonatype/nexus-oss/pull/982

**Comment by adreghiciu** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by djsauble** [comment]
Manual merge https://github.com/sonatype/nexus-oss/commit/1ca2673e2e58633b58d84cd0b17b4b214d898b30

**Pull request closed without merging**
