### PR TITLE
NEXUS-8698: Strict content validation is on by default

### PR DESCRIPTION
**Pull request by cstamas**
Unless overridden.

Depends on
https://github.com/sonatype/nexus-oss/pull/1367
as some tests fails with strict enabled but without fixes/improvements in PR above.

Issue
https://issues.sonatype.org/browse/NEXUS-8698

CI
http://bamboo.s/browse/NX3-OSSF364

### CODE REVIEW

**Comment by jdillon** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by cstamas** [comment]
f2f66f3eb6d65d724d2e5fb6375348122ba486fb

**Pull request closed without merging**
