### PR TITLE
[NEXUS-7834] Bring back check for IsRemotelyAccessibleAttribute on GET

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-7834
http://bamboo.s/browse/NX-OSSF453

### CODE REVIEW

**Comment by mcculls** [comment]
+1 looks reasonable, a test to avoid regressions in this area would be nice though

**Comment by jdillon** [comment]
@mcculls there are no existing UT for this, and I'm not sure if there is a place in an existing IT which would make sense.  I don't think another legacy IT just to check this is worth it.  But perhaps @cstamas knows of a simple way to setup a UT to verify this behavior?

**Comment by cstamas** [comment]
UT added

**Comment by cstamas** [comment]
Manually merged as d4e8982de776d0141481de60f201bccd2560e479

**Pull request closed without merging**
