### PR TITLE
slight optimization by avoiding duplicate File.lastModified()

### PR DESCRIPTION
**Pull request by peterlynch**
slight optimization by avoiding duplicate File.lastModified()

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by mrprescott** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by peterlynch** [comment]
I did not measure what gain this has, but seemingly we are going to native code 2x less frequently than before.

Noticed in a customer thread dump for a heavily loaded Nexus a thread that was checking last modified in this area.

**Pull request merged**
