### PR TITLE
Nexus 8186 windows issues

### PR DESCRIPTION
**Pull request by mkristian**
UTs pass
ITs pass
and manual tests on windows is pending

[WIP]

### CODE REVIEW

**Comment by cstamas** [comment]
+1 change looks ok to me

**Comment by mkristian** [comment]
on my side things look good. did not see any of those exceptions anymore on windows. using both ```gem install some-gem``` and ```bundle install```

ready for review

**Comment by cstamas** [comment]
What's up with this PR? Was it tested on windows?

**Comment by mkristian** [comment]
yes it was tested on windows

**Comment by mcculls** [comment]
+1

**Pull request merged**
