### PR TITLE
Repositions modal dialogs on screen resize

### PR DESCRIPTION
**Pull request by djsauble**
Ensures that modals stick to the center of the screen, improves consistency.

Before: http://take.ms/ViKjf
After: http://take.ms/max1G

+ Removes ‘x’ close icon from modal dialogs
+ Extends NX.view.ModalDialog instead of Ext.window.Window
+ Prevent modals from being resized
+ Give NuGetAPIKey modal proper padding with the nx-inset UI style

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1
Looks like we almost always override the dialog width, might want to minimally provide some constants for S/M/L dialogs rather than custom widths everywhere

**Comment by djsauble** [comment]
Agreed. @mhorvat-sonatype, what were the standard widths you’ve settled on for Lifecycle?

**Comment by jdillon** [comment]
+0 unsure why we care, adding a helper to reduce the modal config is good however.  dont' care too much about resizing.

**Comment by djsauble** [comment]
@jdillon It’s a consistency thing. If we center a dialog, it should remain centered until it’s closed.

Also, Lifecycle behaves this way, so it’s a win-win.

**Comment by mcculls** [comment]
+1

**Comment by jdillon** [comment]
it still odd ux, since the dialog is movable, it will change positions on resize.  IIRC CLM dialogs are not movable, so works better for them.  Though immovable dialogs is also pretty annoying.

**Comment by djsauble** [comment]
@jdillon Hmmm… why do the dialogs need to be movable?

**Comment by djsauble** [comment]
Centering change reverted per sprint review feedback.

https://github.com/sonatype/nexus-oss/commit/b40b653a7f17771f8804c314fc8fc532e2182c2b

**Pull request closed without merging**
