### PR TITLE
delete rubygems file AFTER closing existing read stream on it

### PR DESCRIPTION
**Pull request by mkristian**
this should fix https://issues.sonatype.org/browse/NEXUS-7927

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
+1 though would like some verification this fixes the reported problem, but the change looks sane either way.

**Comment by mkristian** [comment]
I have the verifcation on my TODO first tomorrow

**Comment by mkristian** [comment]
did successfully delete a gem on the hosted repo - ONLY after applying this patch.

**Comment by mcculls** [comment]
+1

**Pull request merged**
