### PR TITLE
Renames CLM to Nexus Lifecycle

### PR DESCRIPTION
**Pull request by djsauble**
fyi @mosabua @jwayman

Related: https://github.com/sonatype/nexus-pro/pull/574

### CODE REVIEW

**Comment by mcculls** [comment]
+1

**Comment by mosabua** [comment]
Imho this is wrong. The data is not from Nexus Lifecycle. It comes from the Sonatype Data Services. It only comes from Nexus Lifecycle if that is actually configured but that is only the case in Nexus Pro+. Not in Nexus OSS or Nexus Pro.

**Comment by kellyrob99** [comment]
@mosabua From a client perspective there is really no distinction, regardless of what we call it. And in any case the update is strictly nomenclature so is no worse than b4

**Comment by mosabua** [comment]
Well.. in the whole renaming process and documentation the agreed upon term is Sonatype Data Services. So imho we should fix it and not make it wrong in a different way.

**Comment by mosabua** [comment]
You could leave out the product names altogether and just use:

Error retrieving component data.

No data available for this component.


I would also remove "Internal components are not covered in Nexus Lifecycle." as this is not always correct. It could have no data even on components that are not internal. In fact that is probably the more common scenario.

**Comment by djsauble** [comment]
Fixed.

**Comment by mosabua** [comment]
Thanks @djsauble  +1 from me ;-)

**Pull request closed without merging**
