### PR TITLE
Use AssistedInject to supply StateGuard enhanced StorageTxImpl instances

### PR DESCRIPTION
**Pull request by mcculls**
To be compared+contrasted with https://github.com/sonatype/nexus-oss/pull/1218

http://bamboo.s/browse/NX3-OSSF208-1

### CODE REVIEW

**Comment by jdillon** [comment]
prefer the proxy impl 0.02, though this could make sense if StorageTX needed to have other injection, but not fond of huge list of assisted prarams, fragile to maintain just to stuff it into guice context.

**Comment by jdillon** [comment]
-1 unless there is otherwise a reason to make StorageTx a guice component.

**Comment by kellyrob99** [comment]
Although I like the Assisted pattern, my vote is also for the competing option.

**Comment by mcculls** [comment]
Closing in favour of https://github.com/sonatype/nexus-oss/pull/1218

**Pull request closed without merging**
