### PR TITLE
Install StateGuardModule as early as possible in the startup sequence.

### PR DESCRIPTION
**Pull request by mcculls**
http://bamboo.s/browse/NX3-OSSF386-2 :white_check_mark: 

Now that nexus-core depends on nexus-repository (and therefore nexus-repository will be processed before nexus-core) it makes more sense to install the StateGuardModule in the root context module instead of waiting until nexus-core is activated, potentially missing out on enhancing prior components. This revealed an incorrect assumption in StorageFacetImpl that hooks would be registered when the facet was in NEW state. Since these hooks are registered by other facets after StorageFacetImpl has been initialised it should instead be checking for INITIALISED state (and use the state constants from FacetSupport).

Also uninstalled the search hook when the search facet is destroyed - otherwise the storage facet could call it when destroying the registry content, even though this is not necessary since the index is gone.

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by mrprescott** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by mcculls** [comment]
Merged to master as 35be827

**Pull request closed without merging**
