### PR TITLE
NEXUS-8607 Raw Format ITs

### PR DESCRIPTION
**Pull request by mrprescott**
Unmangled version of #1340
https://issues.sonatype.org/browse/NEXUS-8607

### CODE REVIEW

**Comment by mrprescott** [comment]
http://bamboo.s/browse/NX3-OSSF333-1 :white_check_mark:

**Comment by mrprescott** [comment]
This PR isn't closed, still needs a couple +1s.

**Comment by mcculls** [comment]
+1

**Comment by mrprescott** [comment]
Manually merged as 9101d66

**Pull request closed without merging**
