### PR TITLE
Merge model modules

### PR DESCRIPTION
**Pull request by jdillon**
Merge *-model modules

related:

https://github.com/sonatype/nexus-pro/pull/540

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
Leaving nexus-ssl-model alone until we sort out re-impl of SSL bits after other changes, and then I'll revisit factoring that out.

**Comment by adreghiciu** [comment]
+1

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
