### PR TITLE
NEXUS-8294 - Add Maven default repos

### PR DESCRIPTION
**Pull request by kellyrob99**
- hosted only, one repo for releases and one for snapshots

https://issues.sonatype.org/browse/NEXUS-8294

Feedback on names is appreciated :)

### CODE REVIEW

**Comment by mosabua** [comment]
Third party is missing ...

**Comment by mosabua** [comment]
And Central proxy ..

**Comment by kellyrob99** [comment]
@mosabua proxy repos are still being impl'd in https://issues.sonatype.org/browse/NEXUS-7683
3rd party could be added, will wait for other folks to comment as to whether or not we want to complify with that at this point.

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Pull request merged**
