### PR TITLE
jmx/mbean sisu integration

### PR DESCRIPTION
**Pull request by jdillon**
Add simple means to bind mbeans and integration with Sisu to automatically bind dynamic-mbeans for annotated components.

Adds use of @ManagedObject in a few places for testing.  Replaces the DebugEventInspector standard-mbeans completely.

Pending some more UT to ensure things work properly.

FTR inspired by jmxutils, but couldn't use it directly due to its narrow public api and use of package-privates for lower-level mbean construction.

### CODE REVIEW

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF120-1 :white_check_mark:

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF120-2 :white_check_mark:

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
