### PR TITLE
NEXUS-8211: store creating repository name in blob header

### PR DESCRIPTION
**Pull request by mcculls**
https://issues.sonatype.org/browse/NEXUS-8211
http://bamboo.s/browse/NX3-OSSF183-3 :white_check_mark:

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by mcculls** [comment]
Manually merged under 4c84ab7

**Comment by adreghiciu** [comment]
+1

**Pull request closed without merging**
