### PR TITLE
[NEXUS-8824] Remove caching security configuration

### PR DESCRIPTION
**Pull request by adreghiciu**
Remove caching security configuration that was in place to avoid going to db to many times. Yet the implementation is wrong as it is not thread safe and it also does not keep track of version field.

Will optimise later if necessary.

https://issues.sonatype.org/browse/NEXUS-8824
http://bamboo.s/browse/NX3-OSSF505

### CODE REVIEW

**Comment by adreghiciu** [comment]
CI :+1:

**Comment by cstamas** [comment]
+1

**Comment by mrprescott** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by jdillon** [comment]
+1

**Pull request merged**
