### PR TITLE
[NEXUS-8415] Move 'online' flag from view-facet to repository core properties

### PR DESCRIPTION
**Pull request by adreghiciu**
https://issues.sonatype.org/browse/NEXUS-8415
http://bamboo.s/browse/NX3-OSSF197

### CODE REVIEW

**Comment by mcculls** [comment]
+1 also suggest the `isOnline` methods from ViewFacet.java and ConfigurableViewFacet.java are removed since they are no longer used and could confuse people going forwards.

**Comment by adreghiciu** [comment]
CI :+1: http://bamboo.s/browse/NX3-OSSF197-1

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
@mcculls Good catch. Removed isOnline() from ViewFacet

**Comment by adreghiciu** [comment]
Manually merged as https://github.com/sonatype/nexus-oss/commit/809b870c5a7e6d8ae28a96add52d8f7c487f2726

**Pull request closed without merging**
