### PR TITLE
[NEXUS-8846] Implement search results sorting as remote sorting via Elastic

### PR DESCRIPTION
**Pull request by adreghiciu**
https://issues.sonatype.org/browse/NEXUS-8846

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by bradbeck** [comment]
It looks like the sorting is case-sensitive, at least for the "Name", i.e. FastInfoSet, UserAgentUtils, activation, aether-api, ...

Is that intentional? I'm not yet familiar with sorting in other parts of the application.

**Comment by kellyrob99** [comment]
@bradbeck I think I have a solution for case-insensitive search if it's an issue

**Comment by joedragons** [comment]
@bradbeck @kellyrob99 I personally think it's an issue and filed on it already (before this)=)  To be triaged?  https://issues.sonatype.org/browse/NEXUS-8844

**Comment by bradbeck** [comment]
As a newb, I expected the search to be case-insensitive. That’s why I asked the question.
I’ll leave it up to the team to say whether or not it is an issue.

-Brad

**Comment by kellyrob99** [comment]
https://github.com/sonatype/nexus-oss/commit/826c4eb6ca9c5ff2d49f907892bf18c089008814 should make the sort case-insensitive using the simplest of the methods described on https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-collations.html#case-insensitive-sorting

**Comment by bradbeck** [comment]
I'm seeing the following exception when I try to perform searches.

https://gist.github.com/bradbeck/afce8eb0d5ef91c90cde

**Comment by kellyrob99** [comment]
@bradbeck did you start with a clean instance? This changes the elasticsearch index structure, so indexes created prior will not work

**Comment by bradbeck** [comment]
@kellyrob99 You called it. Thanks for pointing that out.

**Comment by bradbeck** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by cstamas** [comment]
+1

**Pull request merged**
