### PR TITLE
[2.11.x] NEXUS-7650: Update to tika 1.7

### PR DESCRIPTION
**Pull request by cstamas**
And remove the "hack" for MS PE files (see NEXUS-7603)

Ref
https://github.com/sonatype/nexus-oss/pull/978

Issue
https://issues.sonatype.org/browse/NEXUS-7650

CI
http://bamboo.s/browse/NX-OSSF508

### CODE REVIEW

**Comment by mcculls** [comment]
+1

**Comment by kellyrob99** [comment]
+1 seems reasonable, but did we have any testing in place for this condition previously?

**Comment by adreghiciu** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by cstamas** [comment]
@kellyrob99 no, we did not have and test, this was basically Tika bug. Tika project did absorb our changes and they have test too, see related TIKA issue linked in NEXUS-7650.

**Pull request merged**
