### PR TITLE
NEXUS-8904 support zip functional tests

### PR DESCRIPTION
**Pull request by bradbeck**
https://issues.sonatype.org/browse/NEXUS-8904

### CODE REVIEW

**Comment by adreghiciu** [comment]
+0 I do not think there is to much to be tested in support zip if we do not test the zip creation, so I do not see to much value in this test

**Comment by kellyrob99** [comment]
+1 as it effectively tests the user interaction. Hopefully we test the zip contents as part of UT/IT elsewhere :)

**Comment by jdillon** [comment]
+1 testing the UI here is what a FT should be doing, and if there was a simple way to verify the download we could consider that too but I think that will be problematic in phantomjs at the very least, so this is probably #goodenough

**Comment by mcculls** [comment]
+1

**Pull request merged**
