### PR TITLE
NEXUS-6532: Remove RemoteIpFinder

### PR DESCRIPTION
**Pull request by cstamas**
Seems no more change needed, as Jetty's `ForwardedRequestCustomizer` is already in place.

https://issues.sonatype.org/browse/NEXUS-6532

CI
http://bamboo.s/browse/NX3-OSSF461

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by bradbeck** [comment]
+1

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF461-1 :white_check_mark:

**Comment by jdillon** [comment]
+1

**Pull request merged**
