### PR TITLE
Simplify application of es mapping

### PR DESCRIPTION
**Pull request by jdillon**
Simplifies how formats add ES mapping with support class.  Improve logging of ES mapping configuration generation.

### CODE REVIEW

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF152-1 :white_check_mark:

**Comment by adreghiciu** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
