### PR TITLE
Hookup Paranamer for parameter name discovery

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-8533

related:

https://github.com/sonatype/nexus-pro/pull/538

### CODE REVIEW

**Comment by jdillon** [comment]
After this we can remove most/all of the messages for method-based validation

**Comment by kellyrob99** [comment]
+1 nice simplification for the Component layer

**Comment by adreghiciu** [comment]
Cooool!
+1

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
