### PR TITLE
Clean-up OrientDB signal handlers to avoid dangling references when rebooting

### PR DESCRIPTION
**Pull request by mcculls**
http://bamboo.s/browse/NX3-OSSF433-2 :white_check_mark:

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
Also raised https://github.com/orientechnologies/orientdb/pull/4364 to get this fixed upstream.

**Comment by mcculls** [comment]
Merged to master as d42ba42

**Pull request closed without merging**
