### PR TITLE
Update to OrientDB 2.0.2 hotfix

### PR DESCRIPTION
**Pull request by cstamas**
CI
http://bamboo.s/browse/NX-OSSF569

### CODE REVIEW

**Comment by mcculls** [comment]
+1 ... note there's nothing specific that we need in 2.x, but the WAL improvements are nice-to-have: https://github.com/orientechnologies/orientdb/issues?q=milestone%3A%222.0.2+%28hotfix%29%22

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
+1 post 2.11.2 release

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
