### PR TITLE
Use java.lang.reflect.Proxy to supply StateGuard enhanced StorageTxImpl instances

### PR DESCRIPTION
**Pull request by mcculls**
To be compared+contrasted with https://github.com/sonatype/nexus-oss/pull/1217

http://bamboo.s/browse/NX3-OSSF207-1 :white_check_mark:

### CODE REVIEW

**Comment by jdillon** [comment]
seems useful, and prefer over assisted inject solution for something that is otherwise not a component 0.02

**Comment by jdillon** [comment]
+1

**Comment by kellyrob99** [comment]
+1, in general agreement with @jdillon on this one

**Comment by cstamas** [comment]
+1, but slightly unrelated: what implicit about tx.begin?

**Comment by mcculls** [comment]
@cstamas I don't understand the question - this is about applying the StateGuard aspect around non-Guice created instances, one of which is `StorageTxImpl` which was written to take advantage of this aspect by having `@Guarded` and `@Transitions` annotations, but because it wasn't injected but was created with `new` then it didn't automatically get the aspect.

**Comment by cstamas** [comment]
@mcculls as @mrprescott said, I mixed up the two, the StateGuard and the explicit TX begin fix (that is really unrelated to this PR).

**Comment by mcculls** [comment]
@cstamas np, that will appear in a subsequent PR

**Comment by mcculls** [comment]
Manually merged under b0e745e

**Pull request closed without merging**
