### PR TITLE
NEXUS-8070: Remove of forgotId and forgotPw

### PR DESCRIPTION
**Pull request by cstamas**
As it performs badly on external realms.

Issue
https://issues.sonatype.org/browse/NEXUS-8070

### CODE REVIEW

**Comment by jdillon** [comment]
why not remove the code?

**Comment by cstamas** [comment]
@jdillon I just went with the "simplest solution w/ least impact", as one of my mates described in issue comment :smile:

**Comment by jdillon** [comment]
impact of leaving in commented code that is intended to be removed seems higher than removing it in terms of long term code management.  Only reason we'd leave it in is if we planned to bring it back, which we don't.

**Comment by jdillon** [comment]
anyways, +1 if this removes the crap from the UI and doesn't break any of this very fragile JS

**Comment by cstamas** [comment]
Code removed and locally tested. Extra eyeballs would be nice, to ensure did not break anything.

**Comment by kellyrob99** [comment]
+1

**Pull request merged**
