### PR TITLE
NEXUS-8564 place helpText next to checkbox for checkboxfield

### PR DESCRIPTION
**Pull request by bradbeck**
https://issues.sonatype.org/browse/NEXUS-8564

Before: http://take.ms/Ju8KM
After: http://take.ms/k6lZd

### CODE REVIEW

**Comment by djsauble** [comment]
+1. I really, really like this. I made one small tweak (unrelated to your changes), which pulls the font-size out of the code and into our rapture theme.

In future, consider attaching a screenshot of the change. It helps people grok what you’ve done.

**Comment by jdillon** [comment]
+0 this does fix the help text for that one checkbox, but the bits above also need helptext, which wouldn't be usable in this form.

**Comment by djsauble** [comment]
It also makes forms use vertical space more efficiently, which I think is worthwhile by itself.

Before:
screen shot 2015-07-10 at 3 49 15 pm

After:
screen shot 2015-07-10 at 3 48 51 pm

**Comment by bradbeck** [comment]
Something like this?
screen shot 2015-07-10 at 3 13 09 pm

**Comment by adreghiciu** [comment]
+1

**Comment by bradbeck** [comment]
http://bamboo.s/browse/NX3-OSSF563-TEST-5 :white_check_mark:

**Pull request merged**
