### PR TITLE
Move to official Guice 4.0 distribution

### PR DESCRIPTION
**Pull request by mcculls**
... and bring our guice-servlet customizations into the Nexus codebase.

https://issues.sonatype.org/browse/NEXUS-8532
http://bamboo.s/browse/NX3-OSSF249-1 :white_check_mark:

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1
Any way other than Javadoc that we might document we're overlaying these on top of guice?

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
@kellyrob99 any suggestions? I'm not sure a local readme in the jar would be read any more than the javadoc. Also note that the extra classes sit alongside the ones in guice-servlet, they don't replace any existing classes. They have to be in the same package because the guice-servlet classes currently have limited visibility/extensibility (I'm working with the guice team to resolve this, but they have some internal changes to merge into guice-servlet first).

**Comment by kellyrob99** [comment]
@mcculls No suggestions beyond javadoc, but we've now discussed and documented as part of this PR so I'm happy

**Comment by mcculls** [comment]
Manually merged under e8851ed

**Pull request closed without merging**
