### PR TITLE
Add trace logging concept to UI

### PR DESCRIPTION
**Pull request by jdillon**
Adds trace logging concept to the UI.  This is just console.log (same as debug) but controlled with a flag to reduce default ?debug verbosity.

Can enable with ?debug&trace.

Adds guarding for logging framework calls to avoid overhead when using mode=prod.

Does not use Ext.log anymore, uses console.* instead and adapts for strange browsers.

### CODE REVIEW

**Comment by jdillon** [comment]
should reduce some of the default ?debug logging noise

**Comment by adreghiciu** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
will probably merge this for now until dust settles on other logging changes.

**Comment by mcculls** [comment]
+1 looks ok

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
