### PR TITLE
Extract component to help set base-url.

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-8260

pending port to master

### CODE REVIEW

**Comment by jdillon** [comment]
ftr I hate the name BaseUrlHolderSetter but had to pick something :-P

**Comment by kellyrob99** [comment]
BaseUrlManager?

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF91-2 :white_check_mark:

**Comment by jdillon** [comment]
Renamed to BaseUrlDetector

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX-OSSF642-1 :white_check_mark:

**Comment by mrprescott** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
