### PR TITLE
NEXUS-8821 improve logging of auth token denials

### PR DESCRIPTION
**Pull request by peterlynch**
make it easier to diagnose username mismatch errors

https://issues.sonatype.org/browse/NEXUS-8821

port of https://github.com/sonatype/nexus-oss/pull/1430

### CODE REVIEW

**Comment by jdillon** [comment]
thx @peterlynch 

+1

**Comment by mcculls** [comment]
+1

**Comment by bradbeck** [comment]
+1

**Comment by peterlynch** [comment]
merging now based on @jdillon +1, even though the issue is not in current sprint.

**Pull request merged**
