### PR TITLE
NEXUS-8945 Mapdb memory-mapped files

### PR DESCRIPTION
**Pull request by mrprescott**
This improves performance (it's recommended by MapDB docs), but does not eliminate the deadlock noted by NEXUS-8945.

### CODE REVIEW

**Comment by mcculls** [comment]
+1 btw, what was the result of testing 2.0-beta1?

**Comment by mrprescott** [comment]
As discussed, 2.0-beta1 doesn't appear to be stable enough for us yet.

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by mrprescott** [comment]
Merged as da23274

**Pull request closed without merging**
