### PR TITLE
Nexus 8726 self referential security role fix

### PR DESCRIPTION
**Pull request by kellyrob99**
https://issues.sonatype.org/browse/NEXUS-8726
http://bamboo.s/browse/NX3-OSSF420-1

### CODE REVIEW

**Comment by jdillon** [comment]
+1 very nice, didn't even know ScriptAssert was a thing.  nice way to add validation w/o making type-specific validator impl

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
+1

**Pull request merged**
