### PR TITLE
Update to OrientDB 2.1-rc3

### PR DESCRIPTION
**Pull request by mcculls**
http://bamboo.s/browse/NX3-OSSF427-1 :white_check_mark: 

Also updated NuGet IT expectation to account for slight difference in sorting of text fields.
Text fields are sorted by dictionary order in 2.1.x using Java's Collator (rather than naive
sorting using String.compareTo) which means that 'bar' now appears before 'Foo'.

### CODE REVIEW

**Comment by mrprescott** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
Merged to master as 6fa7a8c

**Pull request closed without merging**
