### PR TITLE
move nexus-groovy-plugin to components/nexus-groovy

### PR DESCRIPTION
**Pull request by jdillon**
Simplify how groovy hooks up to nexus build

related:

https://github.com/sonatype/nexus-pro/pull/526
https://github.com/sonatype/nexus-bundles/pull/138

Also removes nexus-groovyremote-* modules which are no longer needed due to use of pax-exam + groovy integration.

### CODE REVIEW

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF205-1 :white_check_mark:

**Comment by mcculls** [comment]
+1 ... btw, is it also time to remove the nexus-groovyremote-client / nexus-groovyremote-plugin code?

**Comment by jdillon** [comment]
Yup, lets kill it, made obsolete by pax-exam + groovy integration.

—jason




On April 21, 2015 at 6:09:30 PM, Stuart McCulloch (notifications@github.com) wrote:

+1 ... btw, is it also time to remove the nexus-groovyremote-client / nexus-groovyremote-plugin code?

**Comment by adreghiciu** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
http://bamboo.s/browse/NX3-OSSF205-2 :white_check_mark:

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
