### PR TITLE
NEXUS-8902 system information functional tests

### PR DESCRIPTION
**Pull request by bradbeck**
https://issues.sonatype.org/browse/NEXUS-8902

Replaces: https://github.com/sonatype/nexus-oss/pull/1484

### CODE REVIEW

**Comment by jdillon** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by bradbeck** [comment]
http://bamboo.s/browse/NX3-OSSF477-1

There were FT failures but the SupportIT set of FT's passed.

**Pull request merged**
