### PR TITLE
nexus-2.11.x [NEXUS-7860] attach userId during NexusHttpAuthenticationFilter.onLoginSuccess

### PR DESCRIPTION
**Pull request by mcculls**
https://issues.sonatype.org/browse/NEXUS-7860
http://bamboo.s/browse/NX-OSSF904-2 :white_check_mark: 

This handles the case where a subject is not logged in at the time of `SecurityFilter.executeChain`, but is logged in after a challenge is sent. As `SecurityFilter` is not re-executed we need to attach the userId during `NexusHttpAuthenticationFilter.onLoginSuccess`.

This lines up with the two uses of `UserIdMdcHelper.set`: once in `SecurityFilter.executeChain` and once in `NexusWebSecurityManager.login` (which is called from `NexusHttpAuthenticationFilter` for login attempts).

### CODE REVIEW

**Comment by mrprescott** [comment]
+1
Will this need porting to NX3?

**Comment by mcculls** [comment]
@mrprescott yes

**Comment by cstamas** [comment]
+1

**Comment by peterlynch** [comment]
Does this fix siesta resources as well?

**Comment by mcculls** [comment]
@peterlynch yes, it fixes those as well

**Comment by mcculls** [comment]
Merged to 2.11.x as ca3cd12

**Comment by peterlynch** [comment]
awesome - thanks!

**Comment by flopma** [comment]
Hi,

I don't understand by reading Shiro docs why you use the SecurityFilter to get the subject for logging.

Getting it from NexusHttpAuthenticationFilter is not enough (parent of NexusAuthenticationFilter, NexusApiKeyAuthenticationFilter and ContentAuthenticationFilter) ?

**Comment by flopma** [comment]
Hi,

I have created a pull request for a similar functionnality : https://github.com/sonatype/nexus-oss/pull/1624

I think you can merge the code of this pull request (1360) from SecurityFilter and NexusHttpAuthenticationFilter and move it in a overriden executeChain() method in class NexusHttpAuthenticationFilter

**Pull request closed without merging**
