### PR TITLE
NEXUS-7725 Shortens fields in the change password dialog

### PR DESCRIPTION
**Pull request by djsauble**
Issue: https://issues.sonatype.org/browse/NEXUS-7725

Before:
screen shot 2015-01-28 at 12 00 43 pm

After:
screen shot 2015-01-28 at 12 01 00 pm

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by djsauble** [comment]
Manual merge https://github.com/sonatype/nexus-oss/commit/6f5496267346870503d7e2159d7c6d3d3a3ed948

**Pull request closed without merging**
