### PR TITLE
[NEXUS-8537] Split http client builder into own method "prepare"

### PR DESCRIPTION
**Pull request by adreghiciu**
https://issues.sonatype.org/browse/NEXUS-8537

### CODE REVIEW

**Comment by jdillon** [comment]
FTR I specifically left this out, so that folks would use customizers to configure the client and not configure it with the httpclient builder api.

**Comment by adreghiciu** [comment]
Alternative is to ask CLM to change their API. Do we want to wait for that?

**Comment by mcculls** [comment]
+1 for going forwards with this while we work with CLM to update their API/SPI. Might want to add a comment to the prepare method (or mark as `@Deprecated`) to note that it's just there for legacy use.

**Comment by mrprescott** [comment]
+1

**Pull request merged**
