### PR TITLE
[NEXUS-8357] expire remote hashes

### PR DESCRIPTION
**Pull request by mcculls**
https://issues.sonatype.org/browse/NEXUS-8357
http://bamboo.s/browse/NX-OSSF698-4 :white_check_mark:

### CODE REVIEW

**Comment by rseddon** [comment]
Doesn't seem to be working for me in the update case.

1) Set up a proxy repository pointing at another nexus instance.
2) Enabled smart proxy publishing on the remote, and configured the proxy to subscribe with preemptive fetch enabled.
3) PUT a maven-metadata.xml file into the remote, the file is preemptively fetched
4) PUT the maven-metadata.xml.sha1 file into the remote.  The file is preemptively fetched

So far so good.  Now:

5) PUT an updated maven-metadata.xml file into the remote, the file is preemptively fetched
6) PUT an updated maven-metadata.xml.sha1 file into the remote.  The file is not preemptively fetched

And at this point, I can't get the updated sha1 in the proxy, expiring caches does not work, and it seems the automatic refetch triggered by a request to the proxy when remote checksum doesn't match local isn't in place anymore?

**Comment by mcculls** [comment]
@rseddon can you try again with 61b8346? BTW while I was able to recreate the missing hash update (which should be fixed with the latest change) I couldn't recreate the subsequent behaviour after expiring the proxy cache, as that always led to fetching the latest content.

If you still have issues with 61b8346 could you capture a screencast and attach it to NEXUS-8357?

**Comment by mcculls** [comment]
@rseddon also note this PR deliberately doesn't contain the hash mismatch check, this is a different approach which attempts to achieve the same effect without the potential performance impact of the mismatch check

**Comment by rseddon** [comment]
+1, it works now.

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
Manually merged under 9071da4

**Comment by mcculls** [comment]
cherry-picked to master under 9ed63ab

**Pull request closed without merging**
