### PR TITLE
[NEXUS-8664] Replace legacy validation with bean validation

### PR DESCRIPTION
**Pull request by adreghiciu**
https://issues.sonatype.org/browse/NEXUS-8664
http://bamboo.s/browse/NX3-OSSF327

### CODE REVIEW

**Comment by jdillon** [comment]
+1 very nice

**Comment by adreghiciu** [comment]
CI :+1: http://bamboo.s/browse/NX3-OSSF327-1 
One unrelated failure

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
Manually merged https://github.com/sonatype/nexus-oss/commit/db97fb6311056653e00efb008dc59d5b07551ab2

**Pull request closed without merging**
