### PR TITLE
NEXUS-8039: add index for NPM repositoryId property

### PR DESCRIPTION
**Pull request by mcculls**
as it's used in several queries, see https://issues.sonatype.org/browse/NEXUS-8039 for the performance advice

http://bamboo.s/browse/NX-OSSF545-1

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by mcculls** [comment]
Still seeing some performance tips appearing warning about large result sets, so continuing to investigate

**Comment by kellyrob99** [comment]
+1

**Comment by cstamas** [comment]
Verified latest changes, no perf warnings with scenario from the issue. Size of the `packageroot.pagedRepositoryId.sbt` index is 44MB (with repositories as in issue's reproduce case).

**Comment by cstamas** [comment]
Bump. Unless no objections, I will merge this one.

**Comment by mcculls** [comment]
No objections, the alternative is to tune the logging (since this appears to be a situation where adding an index doesn't add much vs the overhead of maintaining it): https://issues.sonatype.org/browse/NEXUS-8039?focusedCommentId=294597&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-294597

**Pull request merged**
