### PR TITLE
Refactors legacy repository UI into a separate rapture plugin

### PR DESCRIPTION
**Pull request by djsauble**
Issue: https://issues.sonatype.org/browse/NEXUS-8007

Related PRs:

https://github.com/sonatype/nexus-pro/pull/491
https://github.com/sonatype/nexus-bundles/pull/131

The old repository views have been put in their own plugin and marked as legacy in the UI. Repository-related strings have been prefixed with `LEGACY_`.

repositories - sonatype nexus 2015-02-25 09-40-01

### CODE REVIEW

**Comment by jdillon** [comment]
Probably do not want to move all the resources (icons), probably not worth trying to move the icons used by legacy either, since those will be re-used most likely for the new ui bits.

**Comment by djsauble** [comment]
Open question to @jdillon, @adreghiciu, and @kellyrob99: what other parts of the UI should be refactored into legacy? Staging rules/profiles, health check, browse repositories, and upload artifacts all come to mind.

**Comment by jdillon** [comment]
@djsauble for now just the things which conflict with what we are rebuilding.  And really if its causing grief we may just remove those for now and rebuild them.

**Comment by adreghiciu** [comment]
+1

**Pull request closed without merging**
