### PR TITLE
NEXUS-8930: NX2 on 304 response drops connection unexpectedly

### PR DESCRIPTION
**Pull request by cstamas**
Reason was that NX2 violates RFC and Jetty just panicked by closing
connection. According to RFC, on 304 response only ETag Header
may be present, and no other entity related header (ie. content length)
should be present: this tricked Jetty into belief response is broken/malformed:
```
contentSent (=0) != contentShouldBeSent (=contentLength header), 
```
Hence, it opted to close connection on it's own.

Best reviewed with `w=0` switch (ignore whitespace).

Issue
https://issues.sonatype.org/browse/NEXUS-8930

CI
http://bamboo.s/browse/NX-OSSF1057

### CODE REVIEW

**Comment by cstamas** [comment]
http://bamboo.s/browse/NX-OSSF1057-1 :+1:

**Comment by mcculls** [comment]
+1

**Comment by mrprescott** [comment]
+1

**Comment by cstamas** [comment]
7fdaea5f82d4ff0336f2118c55625fe1c0a2fb12

**Pull request closed without merging**
