### PR TITLE
NEXUS-8502 password optional

### PR DESCRIPTION
**Pull request by kellyrob99**
https://issues.sonatype.org/browse/NEXUS-8502
http://bamboo.s/browse/NX3-OSSF241-1

### CODE REVIEW

**Comment by jdillon** [comment]
-1 unless there is a valid reason why password should be optional, I think it should be required.

**Comment by adreghiciu** [comment]
I looked into http client and password is not a required field (user name is)

**Comment by kellyrob99** [comment]
Closing for now, will reopen with updated impl to ensure that passwords are required and serialized correctly as per https://issues.sonatype.org/browse/NEXUS-8511

**Comment by djsauble** [comment]
I agree that not being required to set a password looks strange (even if legal).

We could make this behavior clearer by having a “do not set a password” checkbox. If checked, the password field is disabled. If not, the password field can be changed and submitted as normal.

Not for this ticket, obviously, but if there are any other instances in the UI where a password is optional, let’s consider this approach.

**Pull request closed without merging**
