### PR TITLE
[NEXUS-7678] Set karaf.history location to ~/.nexus/karaf.history

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-7678

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by mrprescott** [comment]
+1

**Comment by kellyrob99** [comment]
+1 and out of curiosity, where is the present default location?

**Comment by jdillon** [comment]
@kellyrob99 default is ~/.karaf/karaf.history

**Comment by mcculls** [comment]
+1

**Comment by cstamas** [comment]
+1

**Comment by cwilper** [comment]
+1

**Pull request merged**
