### PR TITLE
[NEXUS-8548] Deprecated use of HttpClient api

### PR DESCRIPTION
**Pull request by adreghiciu**
https://issues.sonatype.org/browse/NEXUS-8548
http://bamboo.s/browse/NX3-OSSF287

* simplified NexusSSLConnectionSocketFactory
* replaced ALLOW_ALL_HOSTNAME_VERIFIER
* dropped unnecessary setStaleConnectionCheckEnabled(false) in DefaultsCustomizer as default value is false and instead disablef validation of pooled connections (this is competing with our connection eviction thread)

### CODE REVIEW

**Comment by cstamas** [comment]
+1 (i kinda remember doing some of these, but it seems am wrong?)

**Comment by adreghiciu** [comment]
CI :+1: http://bamboo.s/browse/NX3-OSSF287-2

**Comment by jdillon** [comment]
+1

**Comment by adreghiciu** [comment]
Manually merged https://github.com/sonatype/nexus-oss/commit/cdb28a2d9b2b327660ba18937990a15faf7d9dd8

**Pull request closed without merging**
