### PR TITLE
NEXUS-8724 snapshot remover performance improvements

### PR DESCRIPTION
**Pull request by peterlynch**
https://issues.sonatype.org/browse/NEXUS-8724

we have already tested the performance improvements of the 2.11.1-01 version of this port:

https://github.com/sonatype/nexus-oss/blob/nexus-2.11.1-01-snapshot_remover_optimizations

### CODE REVIEW

**Comment by peterlynch** [comment]
This doesn't have a noop change from the 2.11.1 port:

https://github.com/sonatype/nexus-oss/commit/3b804c9e3dcbb971b5cee5bd9da99eeff10dc71a#diff-e3c972cb9712c6245a22683f20126b3dR617

This is because the private method is never entered with a hash or signature because of check at 

https://github.com/sonatype/nexus-oss/pull/1371/files#diff-e3c972cb9712c6245a22683f20126b3dR434

**Comment by mcculls** [comment]
looks reasonable

**Comment by jdillon** [comment]
formatting off in many places

otherwise ... /me shrugs okay

**Comment by mcculls** [comment]
+1 ... @cstamas can you do a final review before this is merged since you know this code best?

**Comment by cstamas** [comment]
@mcculls sure, will do

**Comment by cstamas** [comment]
+1

**Pull request merged**
