### PR TITLE
Update OrientDB to 2.0.4

### PR DESCRIPTION
**Pull request by mcculls**
https://github.com/orientechnologies/orientdb/issues?q=milestone%3A2.0.4

http://bamboo.s/browse/NX3-OSSF60-1 :white_check_mark:

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1, should be same done for nexus-2.11.x (npm)?

**Comment by mcculls** [comment]
I'll run a feature build of 2.11.x just in case, but looking at the changelog it should be ok to backport (there's a balance between keeping 2.x dependencies stable and only updating based on feedback vs. always upgrading each release to the latest hotfix)

**Comment by cstamas** [comment]
@mcculls ok, thanks

**Comment by mcculls** [comment]
Merged to master in https://github.com/sonatype/nexus-oss/commit/396862c3f6cd1bb4acccee975d92e667b06d9974

**Pull request closed without merging**
