### PR TITLE
[NEXUS-8589] Add mapping of HttpMethods.MKCOL to BreadActions.ADD

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-8589

### CODE REVIEW

**Comment by jdillon** [comment]
Minimal mapping for what mvn site is bitching about, we may want to improve coverage for more extensions later.

**Comment by mrprescott** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Pull request merged**
