### PR TITLE
[NEXUS-8812] node-id

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-8812

Adds general use node-id facility

### CODE REVIEW

**Comment by jdillon** [comment]
Hooked up to system-info https://www.evernote.com/l/ABKR_HTS64ZHCLRDVszEHNsrO8kfDdGshzM

**Comment by mrprescott** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
manually merged

**Pull request closed without merging**
